### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by StevenAWhite** [AdvancedModularManikin/DDS#3]
I think the build instructions should be updated to indicate that your dependent on 

Fast-RTPS 1.8.X 
Fast-CDR 1.0.9

The current release of Fast-RTPS has refactored a few classes which were in 1.8.X and so the code isn't compatible.  Adding in the Fast-CDR version will just help end users who have never built either as Fast0RTPS 1.8.X is not compatible with the latest release of Fast-CDR either.

Was building off the development branch when I encountered this problem.

**Comment by riggs** [comment]
Some background:
The code in this repo is actually going to be deprecated fairly soon. This repo is currently being maintained to support the existing hardware & software modules that will be used in an upcoming study. A new library is being developed which will be implementing the 1.0 release of the AMM standard, which this repo does not conform to.

That said, the readmes could use an updating to reflect this. @draum ?

**Comment by draum** [comment]
I have updated the root-level READMEs for `master` and `develop` as well as the build instructions for `develop` to indicate that this code is being deprecated in favor of new repositories (a totally new layout, so we aren't reusing this repo) and to add some information regarding FastRTPS building.

**Comment by draum** [comment]
@StevenAWhite The travis script (which is suitable for use from most Debian-based systems) has also been updated: 
https://github.com/AdvancedModularManikin/DDS/blob/develop/travis_scripts/fastrtps.sh

**Comment by StevenAWhite** [comment]
Thanks for the input.
